name: Build

on:
  push:
    branches: [ "1.21" ]
  pull_request:
    branches: [ "1.21" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
    
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build
      
      - name: Upload a Build Artifact (Fabric)
        uses: actions/upload-artifact@v4
        with:
          name: "Fabric"
          path: fabric/build/libs/*.jar
      - name: Upload a Build Artifact (Forge)
        uses: actions/upload-artifact@v4
        with:
          name: "Forge"
          path: forge/build/libs/*.jar
