name: Build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle (with cache)
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Build
        run: |
          ./gradlew --no-daemon build

      - name: Upload built jars
        uses: actions/upload-artifact@v4
        with:
          name: apec-jars
          if-no-files-found: error
          path: |
            build/libs/*.jar
